#
# Configuration for Allen & Heath CQ18T
#
Input:
    Type: 'portmidi'
    Name: 'MIDIMATE II Port 1'
    Channel: 1
Output:
    Name: 'cq'
    Ip: '192.168.178.55'
    Port: 51325
Mappings:
    - Name: 'MuteChannel'
      Control: 0
      Target: 81
      ValueOn: 1
    - Name: 'MuteChannel'
      Control: 1
      Target: 82
      ValueOn: 1
    - Name: 'TapDelay'
      Control: 10
      Target: 2
      ValueOn: 1
    - Name: 'MuteGroup'
      Control: 5
      Target: 0
      ValueOn: 1
    - Name: 'MuteGroup'
      Control: 6
      Target: 1
      ValueOn: 1